### ISSUE TITLE
Cannot compile to WASM

### ISSUE THREAD

**Issue by Wyatt-Stanke** [amethyst/bracket-lib#322]
Whenever I try to compile to WASM, it throws this error:
![image](https://user-images.githubusercontent.com/47758296/205393957-b12bb9b9-a64e-44fe-b9ad-b68e092dbd05.png).

This is my `Cargo.toml`:
```toml
[package]
name = "autoquest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "0.8.7"
bracket-terminal = "0.8.7"
```

This is my `main.rs`:
```rust
bracket_terminal::add_wasm_support!();
use bracket_lib::prelude::*;

struct State {}

impl GameState for State {
    fn tick(&mut self, ctx: &mut BTerm) {
        ctx.print(1, 1, "Hello Bracket World");
    }
}

fn main() -> BError {
    let context = BTermBuilder::simple80x50()
        .with_title("Hello Minimal Bracket World")
        .build()?;

    let gs: State = State {};
    main_loop(context, gs)
}
```

I am using this `Dockerfile` for bug reproduction:
```dockerfile
FROM rustlang/rust:nightly

COPY . .

RUN rustup target add wasm32-unknown-unknown

RUN cargo fetch
RUN cargo build --target wasm32-unknown-unknown
```
This also happens on my computer as well as Docker.
I am on MacOS Monterey Beta running Docker.
